### ISSUE TITLE
Post October 2021 PRR to the OpenTLH twitter account

### ISSUE THREAD

**Issue by shelbygreen** [Open-Data-Tallahassee/records-requests#3]
First need to make an opentlh twitter account. Then post a link to the PDF

**Comment by TheNextCEO** [comment]
Try using this link 
https://docs.google.com/viewer?url=https://github.com/Open-Data-Tallahassee/records-requests/raw/main/data/redacted/October-2021.pdf

**Comment by shelbygreen** [comment]
done!
